
POST http://localhost:3003/products
Content-Type: application/json

{
   "name": "VESTIDO MULA MANGA",
   "tags": ["neutro", "delicado", "balada"]
};

###
GET http://localhost:3003/products/8367




