POST http://localhost:3003/user/users
Content-Type: application/json

{
    "name": "teste4",
    "email": "teste4@email.com",
    "password": "111222"
}

###
POST http://localhost:3003/post/posts1
Content-Type: application/json

{
    "photo": "https://i.pinimg.com/originals/84/92/b5/8492b59087eca943462880307c675cb7.jpg",
    "description": "rapousa",
    "type": "normal",
    "authorId": "36"
}
